### ISSUE TITLE
Getting the CAM for BiT

### ISSUE THREAD

**Issue by sayakpaul** [frgfm/torch-cam#68]
Hi.

I am trying to get CAM for a particular variant of the BiT (Big Transfer) family of ResNets. I think I am providing the the `target_layer` name correctly however I am unable to make it work. 

Here's how the last portion of the model looks like:

```
(norm): GroupNormAct(
    32, 6144, eps=1e-05, affine=True
    (act): ReLU(inplace=True)
  )
  (head): ClassifierHead(
    (global_pool): SelectAdaptivePool2d (pool_type=avg, flatten=False)
    (fc): Conv2d(6144, 1000, kernel_size=(1, 1), stride=(1, 1))
  )
)
```

Here's the error I am getting:

```
KeyError                                  Traceback (most recent call last)
<ipython-input-13-f63345257370> in <module>()
      1 model = timm.create_model('resnetv2_101x3_bitm', pretrained=True).eval()
----> 2 cam_extractor = CAM(model, fc_layer='fc')
      3 
      4 # Get your input
      5 img = read_image("welsh-corgi-1581119_960_720.jpg")

/usr/local/lib/python3.7/dist-packages/torchcam/cams/cam.py in __init__(self, model, target_layer, fc_layer, input_shape)
     62                 raise ValueError("unable to resolve `fc_layer` automatically, please specify its value.")
     63         # Softmax weight
---> 64         self._fc_weights = self.submodule_dict[fc_layer].weight.data
     65 
     66     def _get_weights(self, class_idx: int, scores: Optional[Tensor] = None) -> Tensor:

KeyError: 'fc'
```

The main code:

```python
model = timm.create_model('resnetv2_101x3_bitm', pretrained=True).eval()
cam_extractor = CAM(model, fc_layer='fc')
```

[Here's the Colab Notebook](https://colab.research.google.com/gist/sayakpaul/6ea778de999c70279fbc712793dbeb3e/scratchpad.ipynb) to reproduce the issue.

**Comment by frgfm** [comment]
Hi @sayakpaul :wave: 

There are two things to consider:
1. simply put, the `fc_layer` in your model is not named "fc" in your model state_dict but "head.fc". So that's the easy fix :)
2. In the last release, I actually added an automatic layer name resolution both for the `target_layer` (which you are using since you didn't pass a value), but also for the `fc_layer` (so if you don't specify it, it will find "head.fc" by itself)

Let me you still encounter issues!

**Comment by sayakpaul** [comment]
Thank you for your reply. I will update the comment after I have had a chance to review it.

**Comment by sayakpaul** [comment]
I followed the first suggestion but the activation map that comes out is not suitable for plotting. Here's the [Colab Notebook](https://colab.research.google.com/gist/sayakpaul/2f8300154f613fe1d956ca3e679c28e6/scratchpad.ipynb). 

Once this is worked out I can submit a PR making a fully runnable Colab Notebook including the implementation algorithms that might make it easier for folks to try out this awesome piece of work.

**Comment by frgfm** [comment]
I'll investigate, the tricky part here is that there is no FC in the model but a final conv1x1 layer!
And the base CAM method requires a FC, I'll try to make it compatible

**Comment by sayakpaul** [comment]
Thank you so much!

**Comment by frgfm** [comment]
@sayakpaul if you try again with "head.fc", it should work now ;)

**Comment by sayakpaul** [comment]
Just tried it out but the issue still persists. You can verify this with the Colab Notebook as noted here: https://github.com/frgfm/torch-cam/issues/68#issuecomment-825525591.

**Comment by frgfm** [comment]
But in order to try this, you need to install the project from source (I don't release & publish to pypi every commit :))
Try replacing:
```
pip install torchcam
```
by
```
git clone https://github.com/frgfm/torch-cam.git && git pull && pip install -e torch-cam/. --upgrade
```

Hope this helps!

**Comment by sayakpaul** [comment]
Works like a charm now. 

Could you update here in this thread when you have a chance to release a new version? I would be happy to work on the following:

> Once this is worked out I can submit a PR if you'd like with a fully runnable Colab Notebook including the implementation algorithm. This might make it easier for folks to try out this awesome piece of work.

**Comment by frgfm** [comment]
@sayakpaul I'll try!
But feel free to open a PR at anytime :ok_hand: (do you mean the notebook to be showcasing how to use timm? or is the purpose different?)

**Comment by sayakpaul** [comment]
No no. I want to work on a Colab Notebook to make it easier for folks to get started with `torch-cam` and the algorithms it implements. The Colab Notebook would essentially be what I am currently doing inside the notebook (will include `torchvision` models to reduce the dependency cycle) but with different algorithms that `torch-cam` provides off-the-shelf. 

Let me know if anything is unclear.
